# Generated by Django 4.1.4 on 2023-06-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.CharField(default='0', max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('amenities', models.TextField()),
                ('image', models.ImageField(upload_to='imagestore/')),
                ('type', models.CharField(choices=[('Villa', 'Villa'), ('Flat', 'Flat'), ('House', 'House')], default='Flat', max_length=50)),
            ],
        ),
    ]
